services:
  database:
    image: mariadb:11.5
    container_name: livror-mariadb
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "${DATABASE_PORT:-3306}:3306"
    volumes:
      - ./docker/db-data:/var/lib/mysql:rw
      - ./docker-db-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app
    labels:
        com.symfony.server.service-ignore: true

networks:
  app:
    name: ${APP_NAME}_default
    driver: bridge  